feat(15-matrices) Remove exit, remove sleep

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -20,7 +20,7 @@ jobs:
                     - os: ubuntu-latest
                       node-version: 21.x
                       tag: experimental
-            fail-fast: false
+            fail-fast: true
         runs-on: ubuntu-latest
         steps:
             - name: Setup Node
@@ -30,11 +30,12 @@ jobs:
             - name: Fail if experimental
               if: ${{ matrix.tag == 'experimental' }}
               run: |
-                exit 1
+                # exit 1
+                echo "This should fail"
             - name: Perform some tests
               run: |
                 echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
-                sleep 10
+                # sleep 10
             - name: Upload test results
               run: |
                 echo "Uploading test results"
